Add volume support to cli
KunalBagaria/rustyvibes pull request #24
Opened 2022-11-20 19:49 UTC by aasutossh

`rustyvibes <volume> <soundpack_path>`

Maybe need to update the readme too?
Either update the source in cargo or instruction to build it locally.

2022-11-20 19:50 UTC, aasutossh commented
closes #22 #20

2022-11-20 20:24 UTC, KunalBagaria commented
Thank you so much for the PR, let me review it this week and merge.

2022-11-21 02:50 UTC, aasutossh commented
let me know if anything needs to be improved.
have never used rust before.

2022-11-22 07:07 UTC, KunalBagaria requested changes

2022-11-22 07:07 UTC, KunalBagaria commented on src/play_sound.rs
> +        unsafe { VOLUME = input_volume };
Let's not use unsafe code

2022-11-22 07:07 UTC, KunalBagaria commented on src/play_sound.rs
> +                unsafe { sink.set_volume(VOLUME) };
Will need to remove unsafe blocks

2022-12-09 04:52 UTC, aasutossh commented
Could you provide some insights on how to achieve those actions without `unsafe`?

2022-12-12 17:38 UTC, KunalBagaria commented
You can refer to #25

2022-12-12 17:38 UTC, closed without merging